In [1]:
import numpy as np

# Transpose

In [15]:
sample = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
sample

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
answer = np.transpose(sample)
answer

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [8]:
# convert the mirrored number
n = len(sample)
for i in range(0,n):
    for j in range(i,n):
        temp = sample[i][j]
        sample[i][j] = sample [j][i]
        sample[j][i] = temp
sample
                                  

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

# 90 degree invert the matrix

In [32]:
sample = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

n = len(sample)
for i in range(0,n):
    for j in range(i,n):
        temp = sample[i][j]
        sample[i][j] = sample [j][i]
        sample[j][i] = temp


In [33]:
for i in range(0,n):
    for j in range(0,n//2):
        temp = sample[i][j]
        sample[i][j] = sample[i][n-1-j]
        sample[i][n-1-j] = temp
sample

array([[13,  9,  5,  1],
       [14, 10,  6,  2],
       [15, 11,  7,  3],
       [16, 12,  8,  4]])